import assert from 'node:assert/strict';
import test from 'node:test';
import { loadComponent, mountComponent, api, flushPromises } from './componentsHarness.js';

test('store de estoque mantém carregamento enquanto outra operação estiver pendente', async () => {
  const { createPinia, setActivePinia } = await import('pinia');
  setActivePinia(createPinia());
  const { useStockStore } = await loadComponent('src/stores/stockStore.ts');
  const store = useStockStore();
  const pending = [];
  api.get = () => new Promise((resolve) => pending.push(resolve));
  const inventory = store.fetchInventory();
  const history = store.fetchHistory();
  assert.equal(store.loading, true);
  pending[0]({ data: { metrics: {}, sectors: {}, pagination: {} } });
  await inventory;
  assert.equal(store.loading, true);
  pending[1]({ data: { data: [], total: 0 } });
  await history;
  assert.equal(store.loading, false);
  assert.equal(store.pendingOperations, 0);
});

test('formulário de entrada alterado exige confirmação para cancelar', async () => {
  const { createPinia } = await import('pinia');
  const { createRouter, createMemoryHistory } = await import('vue-router');
  const component = await loadComponent('src/components/SectorFormInput.vue');
  const pinia = createPinia();
  pinia.state.value.auth = { user: { role: 'admin', unit: { code: 'SEST' } }, isAuthenticated: true, availableUnits: [] };
  api.get = async () => ({ data: [] });
  const router = createRouter({ history: createMemoryHistory(), routes: [{ path: '/', component: { template: '<div />' } }] });
  await router.push('/');
  let cancelled = 0;
  const mounted = await mountComponent(component, { pinia, router, props: { onCancel: () => cancelled++ } });
  await flushPromises();
  const input = mounted.element.querySelector('input[type="text"]');
  assert.ok(input);
  input.value = 'ALTERADO';
  input.dispatchEvent(new Event('input', { bubbles: true }));
  await flushPromises();
  window.confirm = () => false;
  const cancel = [...mounted.element.querySelectorAll('button')].find((button) => button.textContent.trim() === 'Cancelar');
  cancel.click();
  await flushPromises();
  assert.equal(cancelled, 0);
  window.confirm = () => true;
  cancel.click();
  await flushPromises();
  assert.equal(cancelled, 1);
  mounted.unmount();
});

for (const role of ['admin', 'admin_setor']) {
test(`estoque restringe destinos de ${role} e registra saída pela API oficial`, async () => {
  const component = await loadComponent('src/pages/InventoryHub.vue');
  const { createPinia } = await import('pinia');
  const { createRouter, createMemoryHistory } = await import('vue-router');
  const pinia = createPinia();
  pinia.state.value.auth = { user: { role, assignedSector: 'CORTE', unit: { code: 'SEST' } }, isAuthenticated: true, availableUnits: [] };
  localStorage.clear();
  let reads = 0;
  let movement;
  api.get = async (url) => {
    if (url !== '/inventory/search') return { data: {} };
    reads++;
    return { data: { metrics: {}, sectors: { corte: { total: 1, data: [{ id: 23, sector: 'CORTE', code: 'MAT-1', name: 'Material', quantity: 5, unit: 'M2', locations: [{ locationId: 1, quantity: 5, location: { id: 1, name: 'A1', sector: 'CORTE' } }] }] } }, pagination: { page: 1, total: 1, totalPages: 1, limit: 50 }, filterOptions: { locations: [{ id: 1, name: 'A1', sector: 'CORTE' }, { id: 2, name: 'A2', sector: 'CORTE' }, { id: 3, name: 'OUTRO-SETOR', sector: 'MONTAGEM' }, { id: 4, name: 'GERAL', sector: null }] } } };
  };
  api.post = async (url, payload) => { movement = { url, payload }; return { data: {} }; };
  const router = createRouter({ history: createMemoryHistory(), routes: [{ path: '/inventory', component }, { path: '/:pathMatch(.*)*', component: { template: '<div />' } }] });
  await router.push('/inventory');
  const mounted = await mountComponent(component, { pinia, router });
  await flushPromises();
  assert.match(mounted.element.textContent, /MAT-1/);
  mounted.element.querySelector('[title="Visualizar Detalhes"]').click();
  await flushPromises();
  const details = mounted.element.querySelector('[aria-label="Detalhes do item de estoque"]');
  assert.match(details.textContent, /MAT-1/);
  assert.ok(details.contains(document.activeElement));
  document.dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape' }));
  await flushPromises();
  assert.equal(Boolean(mounted.element.querySelector('[aria-label="Detalhes do item de estoque"]')), false);
  mounted.element.querySelector('[title="Registrar Movimentação de Estoque"]').click();
  await flushPromises();
  const dialog = mounted.element.querySelector('[aria-label="Movimentação de estoque"]');
  assert.ok(dialog);
  const transfer = [...dialog.querySelectorAll('button')].find(button => button.textContent.trim() === 'TRANSFERÊNCIA');
  assert.ok(transfer);
  transfer.click();
  await flushPromises();
  const destination = dialog.querySelector('select[aria-label="Prateleira de destino"]');
  assert.ok(destination);
  const options = [...destination.options].map(option => option.textContent);
  assert.ok(options.some(text => text.includes('A2')));
  assert.equal(options.some(text => text.includes('GERAL')), role === 'admin');
  assert.ok(options.every(text => !text.includes('OUTRO-SETOR')));
  assert.doesNotMatch(dialog.textContent, /Autorização Admin Master/);
  assert.doesNotMatch(dialog.textContent, /Motivo \/ Origem da Sobra/);
  const exit = [...dialog.querySelectorAll('button')].find(button => button.textContent.trim() === 'SAÍDA');
  exit.click();
  await flushPromises();
  assert.doesNotMatch(dialog.textContent, /Motivo \/ Origem da Sobra/);
  const submit = [...dialog.querySelectorAll('button')].find((button) => button.textContent.includes('Confirmar SAIDA'));
  assert.equal(submit.disabled, false);
  submit.click();
  await flushPromises();
  assert.equal(movement.url, '/inventory/movements');
  assert.equal(movement.payload.stockItemId, 23);
  assert.equal(movement.payload.type, 'SAIDA');
  assert.equal(movement.payload.quantity, 1);
  assert.ok(reads >= 2);
  assert.match(mounted.element.textContent, /registrada com sucesso/);
  assert.equal(Boolean(mounted.element.querySelector('[aria-label="Movimentação de estoque"]')), false);
  mounted.unmount();
});

}
