import assert from 'node:assert/strict';
import test from 'node:test';
import { api, loadComponent, mountComponent, flushPromises } from './componentsHarness.js';

test('troca global informa progresso, mantém identidade e preserva unidade quando falha', async () => {
  const component = await loadComponent('src/components/Layout.vue');
  const { createPinia } = await import('pinia');
  const { createRouter, createMemoryHistory } = await import('vue-router');
  const pinia = createPinia();
  const token = `header.${btoa(JSON.stringify({ id: 17, usuario: 'teste', origem: 'DASS' }))}.signature`;
  pinia.state.value.auth = { user: { id: 17, token, role: 'admin', isGlobalAdmin: true, unit: { code: 'SEST' } }, isAuthenticated: true, availableUnits: [], unitSwitchStatus: '' };
  api.get = async (url) => ({ data: url === '/factory-units' ? [{ code: 'SEST' }, { code: 'VDC' }] : {} });
  let complete;
  api.post = () => new Promise((resolve) => { complete = resolve; });
  const router = createRouter({ history: createMemoryHistory(), routes: [{ path: '/', component: { template: '<div />' } }] });
  await router.push('/');
  const mounted = await mountComponent(component, { pinia, router });
  await flushPromises();
  const selector = mounted.element.querySelector('#global-unit-selector');
  selector.value = 'VDC';
  selector.dispatchEvent(new Event('change'));
  await flushPromises();
  assert.match(mounted.element.textContent, /Trocando unidade/);
  assert.equal(selector.disabled, true);
  complete({ data: { user: { id: 17, role: 'admin' }, unit: { code: 'VDC' }, isGlobalAdmin: true } });
  await flushPromises();
  assert.equal(pinia.state.value.auth.user.token, token);
  assert.equal(pinia.state.value.auth.user.authUserId, '17');
  assert.match(mounted.element.textContent, /Unidade ativa: VDC/);
  mounted.unmount();
  const remounted = await mountComponent(component, { pinia, router });
  await flushPromises();
  assert.match(remounted.element.textContent, /Unidade ativa: VDC/);
  api.post = async () => { throw { response: { data: { error: 'Unidade indisponível' } } }; };
  const nextSelector = remounted.element.querySelector('#global-unit-selector');
  nextSelector.value = 'SEST';
  nextSelector.dispatchEvent(new Event('change'));
  await flushPromises();
  assert.match(remounted.element.querySelector('[role="alert"]').textContent, /Unidade indisponível/);
  assert.equal(pinia.state.value.auth.user.unit.code, 'VDC');
  assert.equal(pinia.state.value.auth.user.token, token);
  assert.equal(nextSelector.value, 'VDC');
  remounted.unmount();
  localStorage.clear();
});
