import assert from 'node:assert/strict';
import test from 'node:test';
import { api, loadComponent, mountComponent, flushPromises } from './componentsHarness.js';

test('troca global informa progresso, mantém identidade e preserva unidade quando falha', async () => {
  const component = await loadComponent('src/components/Layout.vue');
  const { createPinia } = await import('pinia');
  const { createRouter, createMemoryHistory } = await import('vue-router');
  const pinia = createPinia();
  const token = `header.${btoa(JSON.stringify({ id: 17, usuario: 'teste', origem: 'DASS' }))}.signature`;
  pinia.state.value.auth = { user: { id: 17, nome: 'JOSE AUGUSTO DA SILVA', token, role: 'admin', isGlobalAdmin: true, unit: { code: 'SEST' } }, isAuthenticated: true, availableUnits: [], unitSwitchStatus: '' };
  let unitRequests = 0;
  api.get = async (url) => {
    if (url === '/factory-units') unitRequests++;
    return { data: url === '/factory-units' ? [{ code: 'SEST' }, { code: 'VDC' }] : { pendingCount: 2 } };
  };
  let complete;
  api.post = () => new Promise((resolve) => { complete = resolve; });
  const router = createRouter({ history: createMemoryHistory(), routes: [{ path: '/', component: { template: '<div />' } }] });
  await router.push('/');
  const mounted = await mountComponent(component, { pinia, router });
  await flushPromises();
  const selector = mounted.element.querySelector('#global-unit-selector');
  const sidebar = mounted.element.querySelector('aside');
  assert.ok(sidebar.contains(selector));
  assert.equal(mounted.element.querySelector('main header'), null);
  assert.equal(mounted.element.textContent.split('Sobras DASS').length - 1, 1);
  const summary = sidebar.querySelector('[data-user-summary]');
  assert.match(summary.textContent, /JOSE AUGUSTO DA SILVA/);
  assert.match(summary.textContent, /Administrador/);
  assert.doesNotMatch(summary.textContent, /Todos os setores|Admin Master|SEST/);
  assert.ok(summary.querySelector('[aria-label="Requisições pendentes"]'));
  assert.match(summary.querySelector('[aria-label="Requisições pendentes"]').textContent, /2/);
  const menu = mounted.element.querySelector('[aria-label="Abrir menu"]');
  menu.click();
  await flushPromises();
  assert.equal(menu.getAttribute('aria-expanded'), 'true');
  sidebar.querySelector('[aria-label="Fechar menu"]').click();
  await flushPromises();
  assert.equal(menu.getAttribute('aria-expanded'), 'false');
  selector.value = 'VDC';
  selector.dispatchEvent(new Event('change'));
  await flushPromises();
  assert.match(mounted.element.textContent, /Trocando unidade/);
  assert.equal(selector.disabled, true);
  complete({ data: { user: { id: 17, role: 'admin' }, unit: { code: 'VDC' }, isGlobalAdmin: true } });
  await flushPromises();
  assert.equal(pinia.state.value.auth.user.token, token);
  assert.equal(pinia.state.value.auth.user.authUserId, '17');
  assert.match(mounted.element.textContent, /Unidade ativa: VDC/);
  mounted.unmount();
  const remounted = await mountComponent(component, { pinia, router });
  await flushPromises();
  assert.match(remounted.element.textContent, /Unidade ativa: VDC/);
  assert.equal(unitRequests, 1, 'remontar o layout não deve consultar o catálogo novamente');
  api.post = async () => { throw { response: { data: { error: 'Unidade indisponível' } } }; };
  const nextSelector = remounted.element.querySelector('#global-unit-selector');
  nextSelector.value = 'SEST';
  nextSelector.dispatchEvent(new Event('change'));
  await flushPromises();
  assert.match(remounted.element.querySelector('[role="alert"]').textContent, /Unidade indisponível/);
  assert.equal(pinia.state.value.auth.user.unit.code, 'VDC');
  assert.equal(pinia.state.value.auth.user.token, token);
  assert.equal(nextSelector.value, 'VDC');
  remounted.unmount();
  localStorage.clear();
});
