-- Migration neutralizada para evitar poluição do schema public e duplicidade com 0_init.
-- Todas as estruturas de Material, Location, MaterialLocation e Movement já foram provisionadas no schema "sobra_corte".
