ALTER TABLE "sobra_corte"."MaterialRequisition"
  ADD COLUMN "requestUnit" TEXT,
  ADD COLUMN "sourceStockItemIds" INTEGER[] NOT NULL DEFAULT ARRAY[]::INTEGER[],
  ADD COLUMN "sourceCompatibilityIds" INTEGER[] NOT NULL DEFAULT ARRAY[]::INTEGER[],
  ADD COLUMN "sourceSector" "sobra_corte"."SectorType",
  ADD COLUMN "sourceQuantityPerRequestUnit" NUMERIC(18, 6) NOT NULL DEFAULT 1,
  ADD COLUMN "sourceMatchReason" TEXT,
  ADD COLUMN "type" TEXT;

CREATE INDEX "MaterialRequisition_supplier_status_idx"
  ON "sobra_corte"."MaterialRequisition"("factoryUnitId", "sourceSector", "status");

CREATE TABLE "sobra_corte"."RequisitionStockCompatibility" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "factoryUnitId" INTEGER NOT NULL,
  "requestSector" "sobra_corte"."SectorType" NOT NULL,
  "requestSku" TEXT,
  "requestDescription" TEXT,
  "requestModelName" TEXT,
  "requestType" TEXT,
  "requestColor" TEXT,
  "requestSizeGrade" TEXT,
  "requestFootSide" "sobra_corte"."FootSide",
  "matchKey" TEXT NOT NULL,
  "requestUnit" TEXT NOT NULL,
  "sourceStockItemId" INTEGER NOT NULL,
  "sourceSector" "sobra_corte"."SectorType" NOT NULL,
  "sourceQuantityPerRequestUnit" NUMERIC(18, 6) NOT NULL DEFAULT 1,
  "reason" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "RequisitionStockCompatibility_factoryUnitId_fkey"
    FOREIGN KEY ("factoryUnitId") REFERENCES "sobra_corte"."FactoryUnit"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "RequisitionStockCompatibility_sourceStockItemId_factoryUnitId_fkey"
    FOREIGN KEY ("sourceStockItemId", "factoryUnitId") REFERENCES "sobra_corte"."StockItem"("id", "factoryUnitId") ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "RequisitionStockCompatibility_quantity_check"
    CHECK ("sourceQuantityPerRequestUnit" > 0),
  CONSTRAINT "RequisitionStockCompatibility_requestSku_check"
    CHECK ("requestSku" IS NULL OR length(trim("requestSku")) > 0),
  CONSTRAINT "RequisitionStockCompatibility_request_identity_check"
    CHECK ("requestSku" IS NOT NULL OR ("requestDescription" IS NOT NULL AND length(trim("requestDescription")) > 0))
);

CREATE UNIQUE INDEX "RequisitionStockCompatibility_target_source_key"
  ON "sobra_corte"."RequisitionStockCompatibility"("factoryUnitId", "requestSector", "matchKey", "sourceStockItemId");
CREATE INDEX "RequisitionStockCompatibility_target_idx"
  ON "sobra_corte"."RequisitionStockCompatibility"("factoryUnitId", "requestSector", "requestSku");
CREATE INDEX "RequisitionStockCompatibility_target_description_idx"
  ON "sobra_corte"."RequisitionStockCompatibility"("factoryUnitId", "requestSector", "requestDescription");
CREATE INDEX "RequisitionStockCompatibility_source_idx"
  ON "sobra_corte"."RequisitionStockCompatibility"("factoryUnitId", "sourceSector", "sourceStockItemId");
